pipeline{
  agent{
    docker{
    image 'python:2.7.16-slim'
    args '-v $HOME/.m2:/root/.m2'
    }
  } 

  stages{
    stage('build'){
      when{
        changeset "**/vote/**"
      }

      steps{
        echo 'Building vote app'
        dir('vote'){
          pip install -i requirements.txt
        }
      }
    }
   
    stage(test){
      when{
        changeset "**/vote/**"
      }
      steps{
        echo 'Running tests on vote app'
        dir('vote'){
          nosetests -v
        }
      }
    }

  }


  post{
    always{ 
      echo 'Building multibranch pipeline for vote is completed...'
    }
  }
}
