pipeline{
  agent none

  stages{
 
    stage('build'){  
       agent{
        docker{
          image 'python:2.7.16-slim'
          args '--user root'
        }
      } 

      when{
        changeset "**/vote/**"
      }

      steps{
        echo 'Building vote app'
        dir('vote'){
          sh 'pip install -r requirements.txt'
        }
      }
    }
   
    stage(test){
     
      when{
        changeset "**/vote/**"
      }
      steps{
        echo 'Running tests on vote app'
        dir('vote'){
         sh 'pip install -r requirements.txt'
         sh 'nosetests -v'
        }
      }
    }

    stage('docker-package'){
      agent any
      when{
        changeset "**/vote/**"
        branch 'master'
      }
      steps{
        echo "Packagin vote app with docker"
        script{
          docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
            def voteImage = docker.build("abrahambelloso/vote:v${env.BUILD_ID}", "./vote")
            voteImage.push()
            voteImage.push("${env.BRANCH_NAME}")
          }
        }
      }
    }
  } 
}
