pipeline{
  agent none

  stages{
 
    stage('build'){  
       agent{
        docker{
          image 'python:2.7.16-slim'
          args '--user root'
        }
      } 

      when{
        changeset "**/vote/**"
      }

      steps{
        echo 'Building vote app'
        dir('vote'){
          sh 'pip install -r requirements.txt'
        }
      }
    }
   
    stage(test){
       agent{
        docker{
          image 'python:2.7.16-slim'
          args '--user root'
        }
      }  
      when{
        changeset "**/vote/**"
      }
      steps{
        echo 'Running tests on vote app'
        dir('vote'){
         sh 'pip install -r requirements.txt'
         sh 'nosetests -v'
        }
      }
    }

    stage('docker-package'){
      agent any
      when{
        changeset "**/vote/**"
        
      }
      steps{
        echo "Packagin vote app with docker"
        script{
          docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
            def voteImage = docker.build("abrahambelloso/vote:v${env.BUILD_ID}", "./vote")
            voteImage.push()
            voteImage.push("${env.BRANCH_NAME}")
          }
        }
      }
    }
  }


  post{
    always{ 
      echo 'Building multibranch pipeline for vote is completed...'
    }
    failure{
      slackSend (channel: "lfs261", message: "Build Failed! - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open)")
    }
    success{
      slackSend (channel: "lfs261", message: "Build Succeeded! - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open)")
    }
  }
}
